name: CI

env:
  CGO_ENABLED: 0

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x

    - name: Install required dependencies
      run: |
        sudo apt update
        sudo apt-get install -y --no-install-recommends tzdata ca-certificates unzip zip

    - name: Check out code
      uses: actions/checkout@v2

    - name: Generate fakes for testing
      run: go generate ./...

    - name: Run tests
      run: go test ./...

    - name: Build assets
      run: |
        go build -o assets/check ./cmd/check/main.go
        go build -o assets/in ./cmd/in/main.go
        go build -o assets/out ./cmd/out/main.go
